const translations = {
    cs: {
        title: "Spotřebitelský výzkum (CAWI)",
        subtitle: "Akademický výzkum pro diplomovou práci na téma vstupu značky prémiových potravin na trh.",
        welcome: "Vítejte ve výzkumu",
        intro_text: "Tento dotazník je součástí výzkumu trhu pro uvedení nové značky \"Berrie\" (mražené ovoce v čokoládě). Vyplnění zabere 3-4 minuty. Odpovědi jsou plně anonymní a slouží výhradně pro akademické účely.",
        privacy: "🔒 Data nebudou poskytnuta třetím stranám.",
        start_btn: "Začít výzkum",
        q1_title: "1. Demografické údaje",
        q1_age: "Do jaké věkové kategorie spadáte?",
        q1_children: "Máte v domácnosti děti mladší 15 let?",
        yes: "Ano",
        no: "Ne",
        back: "Zpět",
        next: "Další",
        q2_title: "2. Srovnání produktů (Franui vs. Berrie)",
        q2_intro: "Ohodnoťte na škále 1-10 (1 = nejhorší, 10 = nejlepší) následující parametry pro existující argentinskou značku <strong>Franui</strong> (mražené maliny v čokoládě) a náš nový český koncept <strong>Berrie</strong>.",
        concept_title: "Představujeme koncept Berrie",
        concept_desc: "Zcela nový koncept české zdravé pochutiny: <strong>Šokově mražené české ovoce obalené v prémiové dvojité vrstvě čokolády.</strong>",
        concept_points: "<li>✓ Pouze přírodní suroviny, žádná chemie</li><li>✓ Křupavá čokoláda na povrchu, mrazené ovoce uvnitř</li><li>✓ Vyráběno lokálně v ČR z českého ovoce</li>",
        visual_appeal: "Vizuální atraktivita",
        quality_perception: "Vnímaná kvalita surovin",
        health_perception: "Vnímání jako zdravá pochutina",
        q2_intent: "Koupili byste si značku Berrie, pokud by byla dostupná ve vašem obchodě?",
        intent_1: "Určitě ne",
        intent_2: "Spíše ne",
        intent_3: "Nevím",
        intent_4: "Spíše ano",
        intent_5: "Určitě ano",
        q3_title: "3. Cenová citlivost (Berrie 150g)",
        q3_intro: "Běžná velikost balení je 150 gramů (zhruba velikost menší bonboniéry). Na základě vašich dojmů, při jaké ceně za toto balení byste produkt považovali za:",
        psm_1: "Příliš levný (pochybovali byste o kvalitě)",
        psm_2: "Výhodný (skvělý nákup za tuto cenu)",
        psm_3: "Drahý (stále byste zvažovali koupi)",
        psm_4: "Příliš drahý (už byste jej nekoupili)",
        q4_title: "4. Postoje k lokálním potravinám",
        q4_local: "Nakolik je pro vás důležité, aby potraviny byly vyrobeny lokálně?",
        scale_low: "Vůbec (1)",
        scale_high: "Zcela (10)",
        q4_premium: "Jste ochotni zaplatit vyšší cenu za lokální výrobek oproti importovanému?",
        premium_no: "Ne",
        premium_10: "Ano, max do +10 %",
        premium_25: "Ano, +10 % až +25 %",
        premium_more: "Ano, i o více než 25 %",
        submit: "Odeslat dotazník",
        success_title: "Děkujeme za vyplnění!",
        success_text: "Vaše odpovědi byly úspěšně odeslány do akademické databáze."
    },
    en: {
        title: "Consumer Survey (CAWI)",
        subtitle: "Academic market research for a master's thesis on market entry of a premium food brand.",
        welcome: "Welcome to the research",
        intro_text: "This survey is part of market research for the launch of a new brand 'Berrie' (frozen fruit in chocolate). It takes 3-4 minutes. Responses are fully anonymous and for academic purposes only.",
        privacy: "🔒 Data will not be shared with third parties.",
        start_btn: "Start Survey",
        q1_title: "1. Demographics",
        q1_age: "What is your age category?",
        q1_children: "Do you have children under 15 in your household?",
        yes: "Yes",
        no: "No",
        back: "Back",
        next: "Next",
        q2_title: "2. Product Comparison (Franui vs. Berrie)",
        q2_intro: "Rate on a scale of 1-10 (1 = worst, 10 = best) the following parameters for the existing Argentinian brand <strong>Franui</strong> (frozen raspberries in chocolate) and our new Czech concept <strong>Berrie</strong>.",
        concept_title: "Introducing the Berrie Concept",
        concept_desc: "A brand new concept of a Czech healthy snack: <strong>Shock-frozen Czech fruit covered in a premium double layer of chocolate.</strong>",
        concept_points: "<li>✓ Only natural ingredients, no chemicals</li><li>✓ Crunchy chocolate on the outside, frozen fruit inside</li><li>✓ Made locally in the Czech Republic from Czech fruit</li>",
        visual_appeal: "Visual attractiveness",
        quality_perception: "Perceived ingredient quality",
        health_perception: "Perception as a healthy snack",
        q2_intent: "Would you buy the Berrie brand if it were available in your store?",
        intent_1: "Definitely not",
        intent_2: "Probably not",
        intent_3: "Don't know",
        intent_4: "Probably yes",
        intent_5: "Definitely yes",
        q3_title: "3. Price Sensitivity (Berrie 150g)",
        q3_intro: "A typical package is 150 grams. Based on your impressions, at what price for this package would you consider the product to be:",
        psm_1: "Too cheap (you'd doubt the quality)",
        psm_2: "A bargain (great buy at this price)",
        psm_3: "Expensive (but you'd still consider it)",
        psm_4: "Too expensive (you wouldn't buy it)",
        q4_title: "4. Attitudes to Local Food",
        q4_local: "How important is it to you that food is produced locally?",
        scale_low: "Not at all (1)",
        scale_high: "Crucial (10)",
        q4_premium: "Are you willing to pay a premium for a local product over an imported one?",
        premium_no: "No",
        premium_10: "Yes, up to +10%",
        premium_25: "Yes, +10% to +25%",
        premium_more: "Yes, over 25%",
        submit: "Submit Survey",
        success_title: "Thank you!",
        success_text: "Your responses have been securely submitted to the academic database."
    },
    sk: {
        title: "Spotrebiteľský výskum (CAWI)",
        subtitle: "Akademický výskum pre diplomovú prácu na tému vstupu značky prémiových potravín na trh.",
        welcome: "Vitajte vo výskume",
        intro_text: "Tento dotazník je súčasťou výskumu trhu pre uvedenie novej značky \"Berrie\" (mrazené ovocie v čokoláde). Vyplnenie zaberie 3-4 minúty. Odpovede sú plne anonymné a slúžia výhradne na akademické účely.",
        privacy: "🔒 Dáta nebudú poskytnuté tretím stranám.",
        start_btn: "Začať výskum",
        q1_title: "1. Demografické údaje",
        q1_age: "Do akej vekovej kategórie patríte?",
        q1_children: "Máte v domácnosti deti mladšie ako 15 rokov?",
        yes: "Áno",
        no: "Nie",
        back: "Späť",
        next: "Ďalej",
        q2_title: "2. Porovnanie produktov (Franui vs. Berrie)",
        q2_intro: "Ohodnoťte na škále 1-10 (1 = najhoršie, 10 = najlepšie) nasledujúce parametre pre existujúcu argentínsku značku Franui a náš nový český koncept Berrie.",
        concept_title: "Predstavujeme koncept Berrie",
        concept_desc: "Úplne nový koncept českej zdravej pochúťky: <strong>Šokovo mrazené české ovocie obalené v prémiovej dvojitej vrstve čokolády.</strong>",
        concept_points: "<li>✓ Iba prírodné suroviny, žiadna chémia</li><li>✓ Chrumkavá čokoláda na povrchu, mrazené ovocie vnútri</li><li>✓ Vyrábané lokálne v ČR z českého ovocia</li>",
        visual_appeal: "Vizuálna atraktivita",
        quality_perception: "Vnímaná kvalita surovín",
        health_perception: "Vnímanie ako zdravá pochúťka",
        q2_intent: "Kúpili by ste si značku Berrie, ak by bola dostupná vo vašom obchode?",
        intent_1: "Určite nie",
        intent_2: "Skôr nie",
        intent_3: "Neviem",
        intent_4: "Skôr áno",
        intent_5: "Určite áno",
        q3_title: "3. Cenová citlivosť (Berrie 150g)",
        q3_intro: "Bežná veľkosť balenia je 150 gramov. Na základe vašich dojmov, pri akej cene za toto balenie by ste produkt považovali za:",
        psm_1: "Príliš lacný (pochybovali by ste o kvalite)",
        psm_2: "Výhodný (skvelý nákup za túto cenu)",
        psm_3: "Drahý (stále by ste zvažovali kúpu)",
        psm_4: "Príliš drahý (už by ste ho nekúpili)",
        q4_title: "4. Postoje k lokálnym potravinám",
        q4_local: "Nakoľko je pre vás dôležité, aby potraviny boli vyrobené lokálne?",
        scale_low: "Vôbec (1)",
        scale_high: "Úplne (10)",
        q4_premium: "Ste ochotní zaplatiť vyššiu cenu za lokálny výrobok oproti importovanému?",
        premium_no: "Nie",
        premium_10: "Áno, max do +10 %",
        premium_25: "Áno, +10 % až +25 %",
        premium_more: "Áno, aj o viac ako 25 %",
        submit: "Odoslať dotazník",
        success_title: "Ďakujeme za vyplnenie!",
        success_text: "Vaše odpovede boli úspešne odoslané do akademickej databázy."
    },
    uk: {
        title: "Опитування споживачів (CAWI)",
        subtitle: "Академічне дослідження для магістерської роботи на тему виходу на ринок преміального харчового бренду.",
        welcome: "Ласкаво просимо до дослідження",
        intro_text: "Ця анкета є частиною дослідження ринку для запуску нового бренду «Berrie» (заморожені фрукти в шоколаді). Заповнення займе 3-4 хвилини. Відповіді повністю анонімні та використовуються лише для академічних цілей.",
        privacy: "🔒 Дані не будуть передані третім особам.",
        start_btn: "Почати опитування",
        q1_title: "1. Демографічні дані",
        q1_age: "До якої вікової категорії ви належите?",
        q1_children: "Чи є у вашій родині діти віком до 15 років?",
        yes: "Так",
        no: "Ні",
        back: "Назад",
        next: "Далі",
        q2_title: "2. Порівняння продуктів (Franui проти Berrie)",
        q2_intro: "Оцініть за шкалою 1-10 (1 = найгірше, 10 = найкраще) наступні параметри для існуючого аргентинського бренду Franui та нашого нового чеського концепту Berrie.",
        concept_title: "Представляємо концепт Berrie",
        concept_desc: "Абсолютно новий концепт чеських корисних солодощів: <strong>Шоково заморожені чеські фрукти, вкриті подвійним шаром шоколаду.</strong>",
        concept_points: "<li>✓ Тільки натуральні інгредієнти, ніякої хімії</li><li>✓ Хрусткий шоколад зовні, фрукти всередині</li><li>✓ Вироблено локально в Чехії</li>",
        visual_appeal: "Візуальна привабливість",
        quality_perception: "Сприйняття якості інгредієнтів",
        health_perception: "Сприйняття як корисної закуски",
        q2_intent: "Ви б купили Berrie, якби він був у магазині?",
        intent_1: "Точно ні",
        intent_2: "Мабуть, ні",
        intent_3: "Не знаю",
        intent_4: "Мабуть, так",
        intent_5: "Точно так",
        q3_title: "3. Цінова чутливість (Berrie 150г)",
        q3_intro: "Звичайний розмір упаковки – 150 грамів. Виходячи з ваших вражень, за якою ціною за цю упаковку ви б вважали продукт:",
        psm_1: "Занадто дешевим (сумнівалися б у якості)",
        psm_2: "Вигідним (чудова покупка)",
        psm_3: "Дорогим (але все одно розглянули б)",
        psm_4: "Занадто дорогим (уже не купили б)",
        q4_title: "4. Ставлення до місцевих продуктів",
        q4_local: "Наскільки для вас важливо, щоб продукти були вироблені локально?",
        scale_low: "Зовсім ні (1)",
        scale_high: "Дуже важливо (10)",
        q4_premium: "Чи готові ви заплатити вищу ціну за місцевий продукт?",
        premium_no: "Ні",
        premium_10: "Так, макс. до +10 %",
        premium_25: "Так, від +10 % до +25 %",
        premium_more: "Так, навіть більше ніж на 25 %",
        submit: "Надіслати анкету",
        success_title: "Дякуємо за участь!",
        success_text: "Ваші відповіді були успішно надіслані до бази даних."
    },
    vi: {
        title: "Khảo sát người tiêu dùng (CAWI)",
        subtitle: "Nghiên cứu học thuật cho luận văn thạc sĩ.",
        welcome: "Chào mừng bạn đến với khảo sát",
        intro_text: "Bảng câu hỏi này là một phần nghiên cứu thị trường cho sự ra mắt của thương hiệu \"Berrie\" (trái cây đông lạnh bọc sô cô la). Khảo sát mất 3-4 phút và hoàn toàn ẩn danh.",
        privacy: "🔒 Dữ liệu sẽ không được chia sẻ với bên thứ ba.",
        start_btn: "Bắt đầu",
        q1_title: "1. Thông tin nhân khẩu học",
        q1_age: "Bạn thuộc nhóm tuổi nào?",
        q1_children: "Trong nhà có trẻ em dưới 15 tuổi không?",
        yes: "Có",
        no: "Không",
        back: "Quay lại",
        next: "Tiếp theo",
        q2_title: "2. So sánh sản phẩm",
        q2_intro: "Đánh giá từ 1-10 đối với thương hiệu Argentina Franui và sản phẩm mới Berrie của Séc.",
        concept_title: "Khái niệm Berrie",
        concept_desc: "Món ăn nhẹ tốt cho sức khỏe: <strong>Trái cây đông lạnh bọc hai lớp sô cô la.</strong>",
        concept_points: "<li>✓ Nguyên liệu tự nhiên</li><li>✓ Sô cô la giòn bên ngoài</li><li>✓ Sản xuất tại Séc</li>",
        visual_appeal: "Sự hấp dẫn hình ảnh",
        quality_perception: "Chất lượng nguyên liệu",
        health_perception: "Tốt cho sức khỏe",
        q2_intent: "Bạn có mua Berrie không?",
        intent_1: "Chắc chắn không",
        intent_2: "Có lẽ không",
        intent_3: "Không biết",
        intent_4: "Có lẽ có",
        intent_5: "Chắc chắn có",
        q3_title: "3. Độ nhạy cảm về giá (150g)",
        q3_intro: "Ở mức giá nào bạn sẽ coi sản phẩm là:",
        psm_1: "Quá rẻ (nghi ngờ chất lượng)",
        psm_2: "Món hời",
        psm_3: "Đắt (nhưng vẫn cân nhắc)",
        psm_4: "Quá đắt (không mua)",
        q4_title: "4. Thực phẩm địa phương",
        q4_local: "Thực phẩm sản xuất tại địa phương quan trọng như thế nào?",
        scale_low: "Không (1)",
        scale_high: "Rất quan trọng (10)",
        q4_premium: "Bạn có sẵn sàng trả giá cao hơn cho sản phẩm địa phương không?",
        premium_no: "Không",
        premium_10: "Có, tối đa +10%",
        premium_25: "Có, +10% đến +25%",
        premium_more: "Có, hơn 25%",
        submit: "Gửi khảo sát",
        success_title: "Cảm ơn bạn!",
        success_text: "Câu trả lời của bạn đã được gửi thành công."
    },
    ru: {
        title: "Опрос потребителей (CAWI)",
        subtitle: "Академическое исследование для магистерской диссертации о выводе премиального пищевого бренда на рынок.",
        welcome: "Добро пожаловать в исследование",
        intro_text: "Эта анкета является частью исследования рынка для запуска нового бренда «Berrie» (замороженные ягоды в шоколаде). Заполнение займет 3-4 минуты. Ответы полностью анонимны и используются только в академических целях.",
        privacy: "🔒 Данные не будут переданы третьим лицам.",
        start_btn: "Начать опрос",
        q1_title: "1. Демографические данные",
        q1_age: "К какой возрастной категории вы относитесь?",
        q1_children: "Есть ли в вашей семье дети до 15 лет?",
        yes: "Да",
        no: "Нет",
        back: "Назад",
        next: "Далее",
        q2_title: "2. Сравнение продуктов (Franui против Berrie)",
        q2_intro: "Оцените по шкале от 1 до 10 (1 = наихудший, 10 = наилучший) следующие параметры для аргентинского бренда Franui и нашего нового чешского концепта Berrie.",
        concept_title: "Представляем концепт Berrie",
        concept_desc: "Абсолютно новый концепт чешских полезных сладостей: <strong>Шоковой заморозки чешские фрукты, покрытые премиальным двойным слоем шоколада.</strong>",
        concept_points: "<li>✓ Только натуральные ингредиенты, никакой химии</li><li>✓ Хрустящий шоколад снаружи, фрукты внутри</li><li>✓ Произведено локально в Чехии</li>",
        visual_appeal: "Визуальная привлекательность",
        quality_perception: "Восприятие качества ингредиентов",
        health_perception: "Восприятие как полезного снека",
        q2_intent: "Купили бы вы бренд Berrie, если бы он был доступен в вашем магазине?",
        intent_1: "Точно нет",
        intent_2: "Скорее нет",
        intent_3: "Не знаю",
        intent_4: "Скорее да",
        intent_5: "Точно да",
        q3_title: "3. Чувствительность к цене (Berrie 150г)",
        q3_intro: "Обычный размер упаковки – 150 граммов. Исходя из ваших впечатлений, при какой цене за эту упаковку вы бы сочли продукт:",
        psm_1: "Слишком дешевым (усомнились бы в качестве)",
        psm_2: "Выгодным (отличная покупка)",
        psm_3: "Дорогим (но все равно рассмотрели бы)",
        psm_4: "Слишком дорогим (уже не купили бы)",
        q4_title: "4. Отношение к местным продуктам",
        q4_local: "Насколько для вас важно, чтобы продукты производились локально?",
        scale_low: "Совсем нет (1)",
        scale_high: "Очень важно (10)",
        q4_premium: "Готовы ли вы заплатить более высокую цену за местный продукт?",
        premium_no: "Нет",
        premium_10: "Да, макс. до +10 %",
        premium_25: "Да, от +10 % до +25 %",
        premium_more: "Да, даже больше чем на 25 %",
        submit: "Отправить анкету",
        success_title: "Спасибо за участие!",
        success_text: "Ваши ответы были успешно отправлены в базу данных."
    },
    zh: {
        title: "消费者问卷调查 (CAWI)",
        subtitle: "关于高端食品品牌进入市场的硕士论文准学术研究。",
        welcome: "欢迎参与调研",
        intro_text: "本问卷是为推出全新品牌“Berrie”（巧克力脆皮冰冻浆果）所做的市场调研的一部分。只需花费您 3-4 分钟的时间。您的回答完全匿名，并且仅用于学术研究目的。",
        privacy: "🔒 数据绝对保密，不会分享给任何第三方。",
        start_btn: "开始调查",
        q1_title: "1. 人口统计信息",
        q1_age: "您的年龄段是？",
        q1_children: "您家里有15岁以下的儿童吗？",
        yes: "有",
        no: "没有",
        back: "上一步",
        next: "下一步",
        q2_title: "2. 产品对比评估 (Franui vs. Berrie)",
        q2_intro: "请以 1-10 分（1 = 最差，10 = 最好）为现有的阿根廷品牌 Franui 与我们全新的捷克概念品牌 Berrie 进行评分。",
        concept_title: "为您介绍 Berrie 的产品概念",
        concept_desc: "一种源自捷克的全新健康零食概念：<strong>采用极速冷冻技术的捷克本土浆果，外裹双层顶级巧克力。</strong>",
        concept_points: "<li>✓ 100% 天然原料，零化学添加</li><li>✓ 外层巧克力香脆，内层浆果冰爽</li><li>✓ 采用捷克本土水果，捷克当地生产</li>",
        visual_appeal: "视觉吸引力",
        quality_perception: "原料品质的感知",
        health_perception: "作为健康零食的感知",
        q2_intent: "如果您的附近超市有售，您会购买 Berrie 吗？",
        intent_1: "绝对不会",
        intent_2: "大概率不会",
        intent_3: "不确定",
        intent_4: "大概率会",
        intent_5: "肯定会",
        q3_title: "3. 价格敏感度测试 (Berrie 150g)",
        q3_intro: "该产品的常规包装为 150 克。根据您的第一印象，在以下哪种价格下您会认为该产品：",
        psm_1: "太便宜（以至于会怀疑其质量）",
        psm_2: "划算（这个价格买到就是赚到）",
        psm_3: "稍贵（但依然会考虑购买）",
        psm_4: "太贵（以至于绝对不会购买）",
        q4_title: "4. 对本土制造食品的态度",
        q4_local: "您认为食品是“本地制造”这一点对您来说有多重要？",
        scale_low: "完全不重要 (1)",
        scale_high: "极其重要 (10)",
        q4_premium: "您是否愿意为本地制造的产品支付比进口产品更高的价格？",
        premium_no: "不愿意",
        premium_10: "愿意，最多溢价 10%",
        premium_25: "愿意，溢价 10% 到 25%",
        premium_more: "愿意，即使溢价超过 25%",
        submit: "提交问卷",
        success_title: "感谢您的参与！",
        success_text: "您的回答已安全加密并上传至我们的学术数据库中。"
    },
    de: {
        title: "Verbraucherumfrage (CAWI)",
        subtitle: "Akademische Marktforschung für eine Masterarbeit über den Markteintritt einer Premium-Lebensmittelmarke.",
        welcome: "Willkommen zur Umfrage",
        intro_text: "Dieser Fragebogen ist Teil einer Marktforschung für die Einführung der neuen Marke \"Berrie\" (gefrorene Früchte in Schokolade). Das Ausfüllen dauert 3-4 Minuten. Die Antworten sind anonym und dienen ausschließlich akademischen Zwecken.",
        privacy: "🔒 Daten werden nicht an Dritte weitergegeben.",
        start_btn: "Umfrage starten",
        q1_title: "1. Demografische Daten",
        q1_age: "In welche Altersgruppe fallen Sie?",
        q1_children: "Haben Sie Kinder unter 15 Jahren im Haushalt?",
        yes: "Ja",
        no: "Nein",
        back: "Zurück",
        next: "Weiter",
        q2_title: "2. Produktvergleich (Franui vs. Berrie)",
        q2_intro: "Bewerten Sie auf einer Skala von 1-10 (1 = am schlechtesten, 10 = am besten) die folgenden Parameter für die bestehende argentinische Marke Franui und unser neues tschechisches Konzept Berrie.",
        concept_title: "Wir präsentieren das Berrie-Konzept",
        concept_desc: "Ein völlig neues Konzept für einen gesunden tschechischen Snack: <strong>Schockgefrostete tschechische Früchte, umhüllt von einer doppelten Schicht Premium-Schokolade.</strong>",
        concept_points: "<li>✓ Nur natürliche Zutaten, keine Chemie</li><li>✓ Knackige Schokolade außen, gefrorene Früchte innen</li><li>✓ Lokal in der Tschechischen Republik aus tschechischen Früchten hergestellt</li>",
        visual_appeal: "Visuelle Attraktivität",
        quality_perception: "Wahrgenommene Qualität der Zutaten",
        health_perception: "Wahrnehmung als gesunder Snack",
        q2_intent: "Würden Sie die Marke Berrie kaufen, wenn sie in Ihrem Geschäft erhältlich wäre?",
        intent_1: "Auf keinen Fall",
        intent_2: "Eher nein",
        intent_3: "Weiß nicht",
        intent_4: "Eher ja",
        intent_5: "Auf jeden Fall",
        q3_title: "3. Preissensibilität (Berrie 150g)",
        q3_intro: "Die Standardpackung beträgt 150 Gramm. Bei welchem Preis pro Packung würden Sie das Produkt basierend auf Ihren Eindrücken wie folgt betrachten:",
        psm_1: "Zu billig (Zweifel an der Qualität)",
        psm_2: "Günstig (ein toller Kauf)",
        psm_3: "Teuer (würde den Kauf aber noch in Betracht ziehen)",
        psm_4: "Zu teuer (würde es nicht mehr kaufen)",
        q4_title: "4. Einstellung zu lokalen Lebensmitteln",
        q4_local: "Wie wichtig ist es Ihnen, dass Lebensmittel lokal produziert werden?",
        scale_low: "Gar nicht (1)",
        scale_high: "Sehr wichtig (10)",
        q4_premium: "Sind Sie bereit, für ein lokales Produkt einen höheren Preis im Vergleich zu einem importierten zu zahlen?",
        premium_no: "Nein",
        premium_10: "Ja, bis zu +10 %",
        premium_25: "Ja, +10 % bis +25 %",
        premium_more: "Ja, auch um mehr als 25 %",
        submit: "Umfrage absenden",
        success_title: "Vielen Dank für Ihre Teilnahme!",
        success_text: "Ihre Antworten wurden erfolgreich an die akademische Datenbank übermittelt."
    },
    pl: {
        title: "Badanie konsumenckie (CAWI)",
        subtitle: "Akademickie badanie rynku do pracy magisterskiej na temat wejścia na rynek marki żywności premium.",
        welcome: "Witamy w badaniu",
        intro_text: "Ten kwestionariusz jest częścią badania rynku dotyczącego wprowadzenia nowej marki „Berrie” (mrożone owoce w czekoladzie). Wypełnienie zajmuje 3-4 minuty. Odpowiedzi są w pełni anonimowe i służą wyłącznie celom akademickim.",
        privacy: "🔒 Dane nie będą udostępniane osobom trzecim.",
        start_btn: "Rozpocznij badanie",
        q1_title: "1. Dane demograficzne",
        q1_age: "W jakiej grupie wiekowej się znajdujesz?",
        q1_children: "Czy w gospodarstwie domowym są dzieci poniżej 15 roku życia?",
        yes: "Tak",
        no: "Nie",
        back: "Wstecz",
        next: "Dalej",
        q2_title: "2. Porównanie produktów (Franui vs. Berrie)",
        q2_intro: "Oceń w skali 1-10 (1 = najgorzej, 10 = najlepiej) następujące parametry dla istniejącej argentyńskiej marki Franui i naszego nowego czeskiego konceptu Berrie.",
        concept_title: "Przedstawiamy koncept Berrie",
        concept_desc: "Zupełnie nowa koncepcja czeskiej zdrowej przekąski: <strong>Mrożone szokowo czeskie owoce oblane podwójną warstwą czekolady premium.</strong>",
        concept_points: "<li>✓ Tylko naturalne składniki, żadnej chemii</li><li>✓ Chrupiąca czekolada na zewnątrz, mrożone owoce w środku</li><li>✓ Produkowane lokalnie w Czechach z czeskich owoców</li>",
        visual_appeal: "Atrakcyjność wizualna",
        quality_perception: "Postrzegana jakość składników",
        health_perception: "Postrzeganie jako zdrowa przekąska",
        q2_intent: "Czy kupiłbyś markę Berrie, gdyby była dostępna w Twoim sklepie?",
        intent_1: "Zdecydowanie nie",
        intent_2: "Raczej nie",
        intent_3: "Nie wiem",
        intent_4: "Raczej tak",
        intent_5: "Zdecydowanie tak",
        q3_title: "3. Wrażliwość cenowa (Berrie 150g)",
        q3_intro: "Typowe opakowanie to 150 gramów. Na podstawie Twoich wrażeń, przy jakiej cenie za to opakowanie uznałbyś produkt za:",
        psm_1: "Zbyt tani (wątpliwość co do jakości)",
        psm_2: "Korzystny (świetny zakup w tej cenie)",
        psm_3: "Drogi (ale wciąż rozważałbym zakup)",
        psm_4: "Zbyt drogi (już bym go nie kupił)",
        q4_title: "4. Stosunek do lokalnej żywności",
        q4_local: "Jak ważne jest dla Ciebie, aby żywność była produkowana lokalnie?",
        scale_low: "Wcale (1)",
        scale_high: "Bardzo (10)",
        q4_premium: "Czy jesteś gotów zapłacić wyższą cenę za produkt lokalny w porównaniu z importowanym?",
        premium_no: "Nie",
        premium_10: "Tak, do +10%",
        premium_25: "Tak, +10% do +25%",
        premium_more: "Tak, nawet o więcej niż 25%",
        submit: "Wyślij ankietę",
        success_title: "Dziękujemy za wypełnienie!",
        success_text: "Twoje odpowiedzi zostały pomyślnie przesłané do akademickiej bazy danych."
    },
    fr: {
        title: "Sondage auprès des consommateurs (CAWI)",
        subtitle: "Étude de marché académique pour un mémoire de master sur l'entrée sur le marché d'une marque alimentaire premium.",
        welcome: "Bienvenue à l'enquête",
        intro_text: "Ce questionnaire fait partie d'une étude de marché pour le lancement de la nouvelle marque \"Berrie\" (fruits surgelés au chocolat). Le remplissage prend 3-4 minutes. Les réponses sont anonymes et servent exclusivement à des fins académiques.",
        privacy: "🔒 Les données ne seront pas transmises à des tiers.",
        start_btn: "Commencer l'enquête",
        q1_title: "1. Données démographiques",
        q1_age: "À quelle catégorie d'âge appartenez-vous ?",
        q1_children: "Avez-vous des enfants de moins de 15 ans dans votre foyer ?",
        yes: "Oui",
        no: "Non",
        back: "Retour",
        next: "Suivant",
        q2_title: "2. Comparaison de produits (Franui vs. Berrie)",
        q2_intro: "Évaluez sur une échelle de 1 à 10 (1 = le plus mauvais, 10 = le meilleur) les paramètres suivants pour la marque argentine existante Franui et notre nouveau concept tchèque Berrie.",
        concept_title: "Nous présentons le concept Berrie",
        concept_desc: "Un tout nouveau concept de collation tchèque saine : <strong>Fruits tchèques surgelés par choc, enrobés d'une double couche de chocolat premium.</strong>",
        concept_points: "<li>✓ Uniquement des ingrédients naturels, pas de chimie</li><li>✓ Chocolat croquant à l'extérieur, fruits surgelés à l'intérieur</li><li>✓ Produit localement en République tchèque à partir de fruits tchèques</li>",
        visual_appeal: "Attractivité visuelle",
        quality_perception: "Qualité perçue des ingrédients",
        health_perception: "Perception comme collation saine",
        q2_intent: "Achèteriez-vous la marque Berrie si elle était disponible dans votre magasin ?",
        intent_1: "Certainement pas",
        intent_2: "Plutôt non",
        intent_3: "Je ne sais pas",
        intent_4: "Plutôt oui",
        intent_5: "Certainement oui",
        q3_title: "3. Sensibilité au prix (Berrie 150g)",
        q3_intro: "L'emballage standard est de 150 grammes. Sur la base de vos impressions, à quel prix par emballage considéreriez-vous le produit comme suit :",
        psm_1: "Trop bon marché (doute sur la qualité)",
        psm_2: "Bonne affaire (un excellent achat)",
        psm_3: "Cher (mais je l'envisagerais toujours)",
        psm_4: "Trop cher (je ne l'achèterais plus)",
        q4_title: "4. Attitude envers les aliments locaux",
        q4_local: "Quelle importance accordez-vous au fait que les aliments soient produits localement ?",
        scale_low: "Pas du tout (1)",
        scale_high: "Très important (10)",
        q4_premium: "Êtes-vous prêt à payer un prix plus élevé pour un produit local par rapport à un produit importé ?",
        premium_no: "Non",
        premium_10: "Oui, jusqu'à +10 %",
        premium_25: "Oui, +10 % à +25 %",
        premium_more: "Oui, même plus de 25 %",
        submit: "Envoyer l'enquête",
        success_title: "Merci pour votre participation !",
        success_text: "Vos réponses ont été transmises avec succès à la base de données académique."
    },
    it: {
        title: "Sondaggio tra i consumatori (CAWI)",
        subtitle: "Ricerca di mercato accademica per una tesi di master sull'ingresso nel mercato di un marchio alimentare premium.",
        welcome: "Benvenuti al sondaggio",
        intro_text: "Questo questionario fa parte di una ricerca di mercato per il lancio del nuovo marchio \"Berrie\" (frutta surgelata al cioccolato). La compilazione richiede 3-4 minuti. Le risposte sono anonime e servono esclusivamente a scopi accademici.",
        privacy: "🔒 I dati non saranno ceduti a terzi.",
        start_btn: "Inizia il sondaggio",
        q1_title: "1. Dati demografici",
        q1_age: "In quale fascia d'età rientri?",
        q1_children: "Hai bambini sotto i 15 anni in casa?",
        yes: "Sì",
        no: "No",
        back: "Indietro",
        next: "Avanti",
        q2_title: "2. Confronto prodotti (Franui vs. Berrie)",
        q2_intro: "Valuta su una scala da 1 a 10 (1 = peggiore, 10 = migliore) i seguenti parametri per il marchio argentino esistente Franui e il nostro nuovo concetto ceco Berrie.",
        concept_title: "Presentiamo il concetto Berrie",
        concept_desc: "Un concetto completamente nuovo di snack ceco sano: <strong>Frutta ceca surgelata d'urto, ricoperta da un doppio strato di cioccolato premium.</strong>",
        concept_points: "<li>✓ Solo ingredienti naturali, niente chimica</li><li>✓ Cioccolato croccante fuori, frutta surgelata dentro</li><li>✓ Prodotto localmente in Repubblica Ceca da frutta ceca</li>",
        visual_appeal: "Attrattiva visiva",
        quality_perception: "Qualité percepita degli ingredienti",
        health_perception: "Percezione come snack sano",
        q2_intent: "Compreresti il marchio Berrie se fosse disponibile nel tuo negozio?",
        intent_1: "Certamente no",
        intent_2: "Piuttosto no",
        intent_3: "Non lo so",
        intent_4: "Piuttosto sì",
        intent_5: "Certamente sì",
        q3_title: "3. Sensibilità al prezzo (Berrie 150g)",
        q3_intro: "La confezione standard è da 150 grammi. In base alle tue impressioni, a quale prezzo per confezione considereresti il prodotto come segue:",
        psm_1: "Troppo economico (dubbio sulla qualità)",
        psm_2: "Affare (un ottimo acquisto)",
        psm_3: "Caro (ma lo considererei comunque)",
        psm_4: "Troppo caro (non lo comprerei più)",
        q4_title: "4. Atteggiamento verso i prodotti alimentari locali",
        q4_local: "Quanto è importante per te che il cibo sia prodotto localmente?",
        scale_low: "Per niente (1)",
        scale_high: "Molto importante (10)",
        q4_premium: "Sei disposto a pagare un prezzo più alto per un prodotto locale rispetto a uno importato?",
        premium_no: "No",
        premium_10: "Sì, fino al +10%",
        premium_25: "Sì, dal +10% al +25%",
        premium_more: "Sì, anche oltre il 25%",
        submit: "Invia il sondaggio",
        success_title: "Grazie per la partecipazione!",
        success_text: "Le tue risposte sono state inviate correttamente al database accademico."
    },
    es: {
        title: "Encuesta de consumidores (CAWI)",
        subtitle: "Investigación académica para una tesis de maestría sobre la entrada en el mercado de una marca de alimentos premium.",
        welcome: "Bienvenido a la investigación",
        intro_text: "Este cuestionario forma parte de un estudio de mercado para el lanzamiento de la nueva marca \"Berrie\" (fruta congelada en chocolate). Completarlo lleva de 3 a 4 minutos. Las respuestas son anónimas y se utilizan exclusivamente con fines académicos.",
        privacy: "🔒 Los datos no se cederán a terceros.",
        start_btn: "Comenzar la encuesta",
        q1_title: "1. Datos demográficos",
        q1_age: "¿En qué categoría de edad se encuentra?",
        q1_children: "¿Tiene niños menores de 15 años en su hogar?",
        yes: "Sí",
        no: "No",
        back: "Atrás",
        next: "Siguiente",
        q2_title: "2. Comparación de productos (Franui vs. Berrie)",
        q2_intro: "Califique en una escala del 1 al 10 (1 = lo peor, 10 = lo mejor) los siguientes parámetros para la marca argentina existente Franui y nuestro nuevo concepto checo Berrie.",
        concept_title: "Presentamos el concepto Berrie",
        concept_desc: "Un concepto completamente nuevo de snack checo saludable: <strong>Fruta checa congelada por choque, cubierta con una doble capa de chocolate premium.</strong>",
        concept_points: "<li>✓ Solo ingredientes naturales, sin químicos</li><li>✓ Chocolate crujiente por fuera, fruta congelada por dentro</li><li>✓ Producido localmente en la República Checa con fruta checa</li>",
        visual_appeal: "Atractivo visual",
        quality_perception: "Calidad percibida de los ingredientes",
        health_perception: "Percepción como snack saludable",
        q2_intent: "¿Compraría la marca Berrie si estuviera disponible en su tienda?",
        intent_1: "Definitivamente no",
        intent_2: "Probablemente no",
        intent_3: "No lo sé",
        intent_4: "Probablemente sí",
        intent_5: "Definitivamente sí",
        q3_title: "3. Sensibilidad al precio (Berrie 150g)",
        q3_intro: "El envase estándar es de 150 gramos. Según sus impresiones, ¿a qué precio por envase consideraría el producto de la siguiente manera:",
        psm_1: "Demasiado barato (duda sobre la calidad)",
        psm_2: "Ganga (una compra excelente)",
        psm_3: "Caro (pero aún consideraría comprarlo)",
        psm_4: "Demasiado caro (ya no lo compraría)",
        q4_title: "4. Actitud hacia los alimentos locales",
        q4_local: "¿Qué importancia tiene para usted que los alimentos se produzcan localmente?",
        scale_low: "Para nada (1)",
        scale_high: "Muy importante (10)",
        q4_premium: "¿Está dispuesto a pagar un precio más alto por un producto local en comparación con uno importado?",
        premium_no: "No",
        premium_10: "Sí, hasta un +10%",
        premium_25: "Sí, del +10% al +25%",
        premium_more: "Sí, incluso más del 25%",
        submit: "Enviar encuesta",
        success_title: "¡Gracias por su participación!",
        success_text: "Sus respuestas se han enviado correctamente a la base de datos académica."
    },
    hu: {
        title: "Fogyasztói kutatás (CAWI)",
        subtitle: "Akadémiai piackutatás mesterszakos diplomamunkához egy prémium élelmiszer márka piacra lépéséről.",
        welcome: "Üdvözöljük a kutatásban",
        intro_text: "Ez a kérdőív egy piackutatás része az új „Berrie” márka (csokoládéba mártott fagyasztott gyümölcs) bevezetéséhez. A kitöltés 3-4 percet vesz igénybe. A válaszok teljesen névtelenek és kizárólag akadémiai célokat szolgálnak.",
        privacy: "🔒 Az adatokat nem adjuk át harmadik félnek.",
        start_btn: "Kutatás megkezdése",
        q1_title: "1. Demográfiai adatok",
        q1_age: "Melyik korosztályba tartozik?",
        q1_children: "Van-e a háztartásában 15 évnél fiatalabb gyermek?",
        yes: "Igen",
        no: "Nem",
        back: "Vissza",
        next: "Tovább",
        q2_title: "2. Termékösszehasonlítás (Franui vs. Berrie)",
        q2_intro: "Értékelje 1-10-ig terjedő skálán (1 = legrosszabb, 10 = legjobb) a következő paramétereket a meglévő argentin Franui márkára és az új cseh Berrie koncepciónkra.",
        concept_title: "Bemutatjuk a Berrie koncepciót",
        concept_desc: "Egy teljesen új cseh egészséges snack koncepció: <strong>Sokk-fagyasztott cseh gyümölcs, prémium kettős csokoládéréteggel bevonva.</strong>",
        concept_points: "<li>✓ Csak természetes összetevők, semmi vegyszer</li><li>✓ Kívül ropogós csokoládé, belül fagyasztott gyümölcs</li><li>✓ Helyben, Csehországban készül cseh gyümölcsből</li>",
        visual_appeal: "Vizuális vonzerő",
        quality_perception: "Összetevők érzékelt minősége",
        health_perception: "Egészséges snackként való megítélés",
        q2_intent: "Megvásárolná a Berrie márkát, ha elérhető lenne az Ön üzletében?",
        intent_1: "Biztosan nem",
        intent_2: "Inkább nem",
        intent_3: "Nem tudom",
        intent_4: "Inkább igen",
        intent_5: "Biztosan igen",
        q3_title: "3. Árérzékenység (Berrie 150g)",
        q3_intro: "A szokásos csomagolás 150 gramm. Benyomásai alapján milyen csomagonkénti árnál tekintené a terméket a következőnek:",
        psm_1: "Túl olcsó (kétség merülne fel a minőséggel kapcsolatban)",
        psm_2: "Jó vétel (nagyszerű vásárlás ezen az áron)",
        psm_3: "Drága (de még megfontolnám a vásárlást)",
        psm_4: "Túl drága (már nem venném meg)",
        q4_title: "4. Helyi élelmiszerekhez való hozzáállás",
        q4_local: "Mennyire fontos Önnek, hogy az élelmiszerek helyben készüljenek?",
        scale_low: "Egyáltalán nem (1)",
        scale_high: "Nagyon (10)",
        q4_premium: "Hajlandó-e magasabb árat fizetni egy helyi termékért az importálthoz képest?",
        premium_no: "Nem",
        premium_10: "Igen, max. +10%-ig",
        premium_25: "Igen, +10% és +25% között",
        premium_more: "Igen, akár több mint 25%-kal is",
        submit: "Kérdőív beküldése",
        success_title: "Köszönjük a kitöltést!",
        success_text: "Válaszait sikeresen továbbítottuk az akadémiai adatbázisba."
    },
    ro: {
        title: "Sondaj de consum (CAWI)",
        subtitle: "Cercetare academică pentru o teză de masterat privind intrarea pe piață a unui brand alimentar premium.",
        welcome: "Bun venit la cercetare",
        intro_text: "Acest chestionar face parte dintr-un studiu de piață pentru lansarea noului brand „Berrie” (fructe congelate în ciocolată). Completarea durează 3-4 minute. Răspunsurile sunt complet anonime și servesc exclusiv în scopuri academice.",
        privacy: "🔒 Datele nu vor fi furnizate unor terțe părți.",
        start_btn: "Începe cercetarea",
        q1_title: "1. Date demografice",
        q1_age: "În ce categorie de vârstă vă încadrați?",
        q1_children: "Aveți copii sub 15 ani în gospodărie?",
        yes: "Da",
        no: "Nu",
        back: "Înapoi",
        next: "Înainte",
        q2_title: "2. Compararea produselor (Franui vs. Berrie)",
        q2_intro: "Evaluați pe o scară de la 1 la 10 (1 = cel mai slab, 10 = cel mai bun) următorii parametri pentru marca argentiniană existentă Franui și noul nostru concept ceh Berrie.",
        concept_title: "Vă prezentăm conceptul Berrie",
        concept_desc: "Un concept complet nou de gustare cehă sănătoasă: <strong>Fructe cehe congelate prin șoc, acoperite cu un strat dublu de ciocolată premium.</strong>",
        concept_points: "<li>✓ Doar ingrediente naturale, fără substanțe chimice</li><li>✓ Ciocolată crocantă la exterior, fructe congelate la interior</li><li>✓ Produs local în Republica Cehă din fructe cehe</li>",
        visual_appeal: "Atractivitate vizuală",
        quality_perception: "Calitatea percepută a ingredientelor",
        health_perception: "Percepția ca gustare sănătoasă",
        q2_intent: "Ați cumpăra marca Berrie dacă ar fi disponibilă în magazinul dumneavoastră?",
        intent_1: "Categoric nu",
        intent_2: "Mai degrabă nu",
        intent_3: "Nu știu",
        intent_4: "Mai degrabă da",
        intent_5: "Categoric da",
        q3_title: "3. Sensibilitatea la preț (Berrie 150g)",
        q3_intro: "Ambalajul standard este de 150 de grame. Pe baza impresiilor dumneavoastră, la ce preț per ambalaj ați considera produsul astfel:",
        psm_1: "Prea ieftin (ați avea îndoieli cu privire la calitate)",
        psm_2: "Avantajos (o achiziție excelentă la acest preț)",
        psm_3: "Scump (dar tot aș lua în considerare cumpărarea)",
        psm_4: "Prea scump (nu l-aș mai cumpăra)",
        q4_title: "4. Atitudinea față de alimentele locale",
        q4_local: "Cât de important este pentru dumneavoastră ca alimentele să fie produse local?",
        scale_low: "Deloc (1)",
        scale_high: "Foarte (10)",
        q4_premium: "Sunteți dispus să plătiți un preț mai mare pentru un produs local comparativ cu unul importat?",
        premium_no: "Nu",
        premium_10: "Da, până la +10%",
        premium_25: "Da, între +10% și +25%",
        premium_more: "Da, chiar și cu peste 25%",
        submit: "Trimite chestionarul",
        success_title: "Vă mulțumim pentru completare!",
        success_text: "Răspunsurile dumneavoastră au fost trimise cu succes în baza de date academică."
    },
    nl: {
        title: "Consumentenonderzoek (CAWI)",
        subtitle: "Academisch marktonderzoek voor een masterscriptie over de markttoegang van een premium voedingsmerk.",
        welcome: "Welkom bij het onderzoek",
        intro_text: "Deze vragenlijst maakt deel uit van een marktonderzoek voor de lancering van het nieuwe merk \"Berrie\" (bevroren fruit in chocolade). Het invullen duurt 3-4 minuten. De antwoorden zijn volledig anoniem en dienen uitsluitend voor academische doeleinden.",
        privacy: "🔒 Gegevens worden niet aan derden verstrekt.",
        start_btn: "Start onderzoek",
        q1_title: "1. Demografische gegevens",
        q1_age: "In welke leeftijdscategorie valt u?",
        q1_children: "Heeft u kinderen onder de 15 jaar in uw huishouden?",
        yes: "Ja",
        no: "Nee",
        back: "Terug",
        next: "Volgende",
        q2_title: "2. Productvergelijking (Franui vs. Berrie)",
        q2_intro: "Beoordeel op een schaal van 1-10 (1 = slechtste, 10 = beste) de volgende parameters voor het bestaande Argentijnse merk Franui and ons nieuwe Tsjechische concept Berrie.",
        concept_title: "Introductie van het Berrie-concept",
        concept_desc: "Een gloednieuw concept van een Tsjechische gezonde snack: <strong>Shock-bevroren Tsjechisch fruit omhuld met een premium dubbele laag chocolade.</strong>",
        concept_points: "<li>✓ Alleen natuurlijke ingrediënten, geen chemie</li><li>✓ Krokante chocolade van buiten, bevroren fruit van binnen</li><li>✓ Lokaal geproduceerd in Tsjechië van Tsjechisch fruit</li>",
        visual_appeal: "Visuele aantrekkingskracht",
        quality_perception: "Waargenomen kwaliteit van ingrediënten",
        health_perception: "Perceptie als gezonde snack",
        q2_intent: "Zou u het merk Berrie kopen als het in uw winkel verkrijgbaar zou zijn?",
        intent_1: "Zeker niet",
        intent_2: "Waarschijnlijk niet",
        intent_3: "Weet ik niet",
        intent_4: "Waarschijnlijk wel",
        intent_5: "Zeker wel",
        q3_title: "3. Prijsgevoeligheid (Berrie 150g)",
        q3_intro: "Een standaardverpakking is 150 gram. Op basis van uw indrukken, bij welke prijs per verpakking zou u het product als volgt beschouwen:",
        psm_1: "Te goedkoop (u zou twijfelen aan de kwaliteit)",
        psm_2: "Koopje (een geweldige koop voor deze prijs)",
        psm_3: "Duur (maar ik zou het nog steeds overwegen)",
        psm_4: "Te duur (ik zou het niet meer kopen)",
        q4_title: "4. Houding tegenover lokale voeding",
        q4_local: "Hoe belangrijk is het voor u dat voedsel lokaal wordt geproduceerd?",
        scale_low: "Helemaal niet (1)",
        scale_high: "Heel erg (10)",
        q4_premium: "Bent u bereid een hogere prijs te betalen voor een lokaal product vergeleken met een geïmporteerd product?",
        premium_no: "Nee",
        premium_10: "Ja, tot +10%",
        premium_25: "Ja, +10% tot +25%",
        premium_more: "Ja, zelfs meer dan 25%",
        submit: "Vragenlijst verzenden",
        success_title: "Bedankt voor het invullen!",
        success_text: "Uw antwoorden zijn succesvol verzonden naar de academische database."
    },
    pt: {
        title: "Pesquisa de Consumo (CAWI)",
        subtitle: "Pesquisa de mercado académica para uma tese de mestrado sobre a entrada no mercado de uma marca de alimentos premium.",
        welcome: "Bem-vindo à pesquisa",
        intro_text: "Este questionário faz parte de um estudo de mercado para o lançamento da nova marca \"Berrie\" (fruta congelada em chocolate). O preenchimento demora 3-4 minutos. As respostas são totalmente anónimas e servem exclusivamente para fins académicos.",
        privacy: "🔒 Os dados não serão cedidos a terceiros.",
        start_btn: "Iniciar pesquisa",
        q1_title: "1. Dados demográficos",
        q1_age: "Em que faixa etária se encontra?",
        q1_children: "Tem crianças com menos de 15 anos no seu agregado familiar?",
        yes: "Sim",
        no: "Não",
        back: "Voltar",
        next: "Próximo",
        q2_title: "2. Comparação de produtos (Franui vs. Berrie)",
        q2_intro: "Avalie numa escala de 1 a 10 (1 = o pior, 10 = o melhor) os seguintes parâmetros para a marca argentina existente Franui e o nosso novo conceito checo Berrie.",
        concept_title: "Apresentamos o conceito Berrie",
        concept_desc: "Um conceito totalmente novo de snack checo saudável: <strong>Fruta checa congelada por choque, coberta com uma camada dupla de chocolate premium.</strong>",
        concept_points: "<li>✓ Apenas ingredientes naturais, sem químicos</li><li>✓ Chocolate crocante por fora, fruta congelada por dentro</li><li>✓ Produzido localmente na República Checa com fruta checa</li>",
        visual_appeal: "Atratividade visual",
        quality_perception: "Qualidade percebida dos ingredientes",
        health_perception: "Perceção como snack saudável",
        q2_intent: "Compraria a marca Berrie se estivesse disponível na sua loja?",
        intent_1: "Certamente não",
        intent_2: "Provavelmente não",
        intent_3: "Não sei",
        intent_4: "Provavelmente sim",
        intent_5: "Certamente sim",
        q3_title: "3. Sensibilidade ao preço (Berrie 150g)",
        q3_intro: "A embalagem padrão é de 150 gramas. Com base nas suas impressões, a que preço por embalagem consideraria o produto da seguinte forma:",
        psm_1: "Demasiado barato (duvidaria da qualidade)",
        psm_2: "Boa compra (uma excelente compra por este preço)",
        psm_3: "Caro (mas ainda consideraria comprar)",
        psm_4: "Demasiado caro (já não o compraria)",
        q4_title: "4. Atitude em relação aos alimentos locais",
        q4_local: "Qual a importância que atribui ao facto de os alimentos serem produzidos localmente?",
        scale_low: "Nenhuma (1)",
        scale_high: "Muita (10)",
        q4_premium: "Está disposto a pagar um preço mais elevado por um produto local em comparação com um importado?",
        premium_no: "Não",
        premium_10: "Sim, até +10%",
        premium_25: "Sim, entre +10% e +25%",
        premium_more: "Sim, mesmo mais de 25%",
        submit: "Enviar questionário",
        success_title: "Obrigado por preencher!",
        success_text: "As suas respostas foram enviadas com sucesso para a base de dados académica."
    },
    el: {
        title: "Έρευνα Καταναλωτών (CAWI)",
        subtitle: "Ακαδημαϊκή έρευνα αγοράς για μεταπτυχιακή εργασία σχετικά με την είσοδο στην αγορά μιας μάρκας τροφίμων premium.",
        welcome: "Καλώς ήρθατε στην έρευνα",
        intro_text: "Αυτό το ερωτηματολόγιο αποτελεί μέρος μιας έρευνας αγοράς για την κυκλοφορία της νέας μάρκας \"Berrie\" (κατεψυγμένα φρούτα σε σοκολάτα). Η συμπλήρωση διαρκεί 3-4 λεπτά. Οι απαντήσεις είναι πλήρως ανώνυμες και χρησιμεύουν αποκλειστικά για ακαδημαϊκούς σκοπούς.",
        privacy: "🔒 Τα δεδομένα δεν θα δοθούν σε τρίτους.",
        start_btn: "Έναρξη έρευνας",
        q1_title: "1. Δημογραφικά στοιχεία",
        q1_age: "Σε ποια ηλικιακή κατηγορία ανήκετε;",
        q1_children: "Έχετε παιδιά κάτω των 15 ετών στο νοικοκυριό σας;",
        yes: "Ναι",
        no: "Όχι",
        back: "Πίσω",
        next: "Επόμενο",
        q2_title: "2. Σύγκριση προϊόντων (Franui vs. Berrie)",
        q2_intro: "Βαθμολογήστε σε μια κλίμακα 1-10 (1 = χειρότερο, 10 = καλύτερο) τις ακόλουθες παραμέτρους για την υπάρχουσα αργεντίνικη μάρκα Franui και το νέο μας τσεχικό κόνσεπτ Berrie.",
        concept_title: "Παρουσίαση του Berrie Concept",
        concept_desc: "Ένα ολοκαίνουργιο κόνσεπτ τσεχικού υγιεινού σνακ: <strong>Τσεχικά φρούτα ταχείας κατάψυξης, καλυμμένα με μια premium διπλή στρώση σοκολάτας.</strong>",
        concept_points: "<li>✓ Μόνο φυσικά συστατικά, χωρίς χημικά</li><li>✓ Τραγανή σοκολάτα εξωτερικά, κατεψυγμένα φρούτα εσωτερικά</li><li>✓ Παράγεται τοπικά στην Τσεχία από τσεχικά φρούτα</li>",
        visual_appeal: "Οπτική ελκυστικότητα",
        quality_perception: "Αντιλαμβανόμενη ποιότητα συστατικών",
        health_perception: "Αντίληψη ως υγιεινό σνακ",
        q2_intent: "Θα αγοράζατε τη μάρκα Berrie εάν ήταν διαθέσιμη στο κατάστημά σας;",
        intent_1: "Σίγουρα όχι",
        intent_2: "Μάλλον όχι",
        intent_3: "Δεν ξέρω",
        intent_4: "Μάλλον ναι",
        intent_5: "Σίγουρα ναι",
        q3_title: "3. Ευαισθησία τιμής (Berrie 150g)",
        q3_intro: "Η τυπική συσκευασία είναι 150 γραμμάρια. Με βάση τις εντυπώσεις σας, σε ποια τιμή ανά συσκευασία θα θεωρούσατε το προϊόν ως εξής:",
        psm_1: "Πολύ φθηνό (θα αμφιβάλλατε για την ποιότητα)",
        psm_2: "Ευκαιρία (μια εξαιρετική αγορά σε αυτή την τιμή)",
        psm_3: "Ακριβό (αλλά θα εξακολουθούσα να σκέφτομαι να το αγοράσω)",
        psm_4: "Πολύ ακριβό (δεν θα το αγόραζα πια)",
        q4_title: "4. Στάση απέναντι στα τοπικά τρόφιμα",
        q4_local: "Πόσο σημαντικό είναι για εσάς τα τρόφιμα να παράγονται τοπικά;",
        scale_low: "Καθόλου (1)",
        scale_high: "Πολύ (10)",
        q4_premium: "Είστε διατεθειμένοι να πληρώσετε υψηλότερη τιμή για ένα τοπικό προϊόν σε σύγκριση με ένα εισαγόμενο;",
        premium_no: "Όχι",
        premium_10: "Ναι, έως +10%",
        premium_25: "Ναι, +10% έως +25%",
        premium_more: "Ναι, ακόμη και πάνω από 25%",
        submit: "Υποβολή ερωτηματολογίου",
        success_title: "Σας ευχαριστούμε για τη συμπλήρωση!",
        success_text: "Οι απαντήσεις σας στάλθηκαν με επιτυχία στην ακαδημαϊκή βάση δεδομένων."
    },
    sv: {
        title: "Konsumentundersökning (CAWI)",
        subtitle: "Akademisk marknadsundersökning för en masteruppsats om marknadsinträde för ett premiumlivsmedelsvarumärke.",
        welcome: "Välkommen till undersökningen",
        intro_text: "Detta frågeformulär är en del av en marknadsundersökning för lanseringen av det nya varumärket \"Berrie\" (fryst frukt i choklad). Det tar 3-4 minuter att fylla i. Svaren är helt anonyma och tjänar uteslutande akademiska syften.",
        privacy: "🔒 Uppgifterna kommer inte att lämnas ut till tredje part.",
        start_btn: "Starta undersökningen",
        q1_title: "1. Demografiska uppgifter",
        q1_age: "Vilken ålderskategori tillhör du?",
        q1_children: "Har du barn under 15 år i ditt hushåll?",
        yes: "Ja",
        no: "Nej",
        back: "Tillbaka",
        next: "Nästa",
        q2_title: "2. Produktjämförelse (Franui vs. Berrie)",
        q2_intro: "Betygsätt på en skala från 1-10 (1 = sämst, 10 = bäst) följande parametrar för det befintliga argentinska varumärket Franui och vårt nya tjeckiska koncept Berrie.",
        concept_title: "Vi presenterar Berrie-konceptet",
        concept_desc: "Ett helt nytt koncept för ett tjeckiskt hälsosamt mellanmål: <strong>Snabbfryst tjeckisk frukt täckt med ett dubbelt lager premiumchoklad.</strong>",
        concept_points: "<li>✓ Endast naturliga ingredienser, ingen kemi</li><li>✓ Knaprig choklad på utsidan, fryst frukt inuti</li><li>✓ Tillverkas lokalt i Tjeckien av tjeckisk frukt</li>",
        visual_appeal: "Visuell attraktivitet",
        quality_perception: "Uppfattad kvalitet på ingredienser",
        health_perception: "Uppfattning som ett hälsosamt mellanmål",
        q2_intent: "Skulle du köpa varumärket Berrie om det fanns tillgängligt i din butik?",
        intent_1: "Definitivt inte",
        intent_2: "Snarare inte",
        intent_3: "Vet ej",
        intent_4: "Snarare ja",
        intent_5: "Definitivt ja",
        q3_title: "3. Priskänslighet (Berrie 150g)",
        q3_intro: "Standardförpackningen är 150 gram. Baserat på dina intryck, vid vilket pris per förpackning skulle du betrakta produkten som följer:",
        psm_1: "För billig (tveksamhet om kvaliteten)",
        psm_2: "Prisvärd (ett bra köp för detta pris)",
        psm_3: "Dyr (men skulle fortfarande överväga köp)",
        psm_4: "För dyr (skulle inte köpa den längre)",
        q4_title: "4. Inställning till lokal mat",
        q4_local: "Hur viktigt är det för dig att maten produceras lokalt?",
        scale_low: "Inte alls (1)",
        scale_high: "Mycket viktigt (10)",
        q4_premium: "Är du villig att betala ett högre pris för en lokal produkt jämfört med en importerad?",
        premium_no: "Nej",
        premium_10: "Ja, upp till +10%",
        premium_25: "Ja, +10% till +25%",
        premium_more: "Ja, till och med mer än 25%",
        submit: "Skicka enkät",
        success_title: "Tack för att du fyllde i enkäten!",
        success_text: "Dina svar har skickats till den akademiska databasen."
    },
    da: {
        title: "Forbrugerundersøgelse (CAWI)",
        subtitle: "Akademisk markedsundersøgelse til et speciale om markedsindtræden for et premium fødevaremærke.",
        welcome: "Velkommen til undersøgelsen",
        intro_text: "Dette spørgeskema er en del af en markedsundersøgelse til lanceringen af det nye mærke \"Berrie\" (frossen frugt i chokolade). Det tager 3-4 minutter at udfylde. Svarene er fuldstændig anonyme og tjener udelukkende akademiske formål.",
        privacy: "🔒 Data vil ikke blive videregivet til tredjeparter.",
        start_btn: "Start undersøgelse",
        q1_title: "1. Demografiske data",
        q1_age: "Hvilken alderskategori tilhører du?",
        q1_children: "Har du børn under 15 år i din husstand?",
        yes: "Ja",
        no: "Nej",
        back: "Tilbage",
        next: "Næste",
        q2_title: "2. Produktsammenligning (Franui vs. Berrie)",
        q2_intro: "Bedøm på en skala fra 1-10 (1 = dårligst, 10 = bedst) følgende parametre for det eksisterende argentinske mærke Franui og vores nye tjekkiske koncept Berrie.",
        concept_title: "Vi præsenterer Berrie-konceptet",
        concept_desc: "Et helt nyt koncept for en tjekkisk sund snack: <strong>Chokfrosset tjekkisk frugt dækket med et premium dobbelt lag chokolade.</strong>",
        concept_points: "<li>✓ Kun naturlige ingredienser, ingen kemi</li><li>✓ Sprød chokolade udvendigt, frossen frugt indvendigt</li><li>✓ Produceret lokalt i Tjekkiet af tjekkisk frugt</li>",
        visual_appeal: "Visuel appel",
        quality_perception: "Opfattet kvalitet af ingredienser",
        health_perception: "Opfattelse som en sund snack",
        q2_intent: "Ville du købe mærket Berrie, hvis det var tilgængeligt i din butik?",
        intent_1: "Bestemt ikke",
        intent_2: "Snarere ikke",
        intent_3: "Ved ikke",
        intent_4: "Snarere ja",
        intent_5: "Bestemt ja",
        q3_title: "3. Prisfølsomhed (Berrie 150g)",
        q3_intro: "Standardemballagen er 150 gram. Baseret på dine indtryk, ved hvilken pris pr. emballage ville du betragte produktet som følger:",
        psm_1: "For billig (tvivl om kvaliteten)",
        psm_2: "Godt køb (et fantastisk køb til denne pris)",
        psm_3: "Dyr (men ville stadig overveje køb)",
        psm_4: "For dyr (ville ikke købe det længere)",
        q4_title: "4. Holdning til lokal mad",
        q4_local: "Hvor vigtigt er det for dig, at maden er produceret lokalt?",
        scale_low: "Slet ikke (1)",
        scale_high: "Meget vigtigt (10)",
        q4_premium: "Er du villig til at betale en højere pris for et lokalt produkt sammenlignet med et importeret?",
        premium_no: "Nej",
        premium_10: "Ja, op til +10%",
        premium_25: "Ja, +10% til +25%",
        premium_more: "Ja, selv mere end 25%",
        submit: "Send undersøgelse",
        success_title: "Tak fordi du udfyldte undersøgelsen!",
        success_text: "Dine svar er blevet sendt til den akademiske database."
    },
    fi: {
        title: "Kuluttajatutkimus (CAWI)",
        subtitle: "Akateeminen markkinatutkimus pro gradu -tutkielmaa varten premium-elintarvikebrändin markkinoille tuloa varten.",
        welcome: "Tervetuloa tutkimukseen",
        intro_text: "Tämä kyselylomake on osa markkinatutkimusta uuden Berrie-brändin (pakastetut hedelmät suklaassa) lanseerausta varten. Täyttäminen kestää 3-4 minuuttia. Vastaukset ovat täysin nimettömiä ja palvelevat ainoastaan akateemisia tarkoituksia.",
        privacy: "🔒 Tietoja ei luovuteta kolmansille osapuolille.",
        start_btn: "Aloita tutkimus",
        q1_title: "1. Demografiset tiedot",
        q1_age: "Mihin ikäryhmään kuulut?",
        q1_children: "Onko taloudessasi alle 15-vuotiaita lapsia?",
        yes: "Kyllä",
        no: "Ei",
        back: "Takaisin",
        next: "Seuraava",
        q2_title: "2. Tuotevertailu (Franui vs. Berrie)",
        q2_intro: "Arvioi asteikolla 1-10 (1 = huonoin, 10 = paras) seuraavat parametrit olemassa olevalle argentiinalaiselle Franui-brändille ja uudelle tšekkiläiselle Berrie-konseptillemme.",
        concept_title: "Esittelyssä Berrie-konsepti",
        concept_desc: "Täysin uusi tšekkiläinen terveellinen välipalakonsepti: <strong>Pikapakastettuja tšekkiläisiä hedelmiä, jotka on päällystetty ensiluokkaisella kaksinkertaisella suklaakerroksella.</strong>",
        concept_points: "<li>✓ Vain luonnollisia ainesosia, ei kemiaa</li><li>✓ Rapea suklaa päällä, pakastetut hedelmät sisällä</li><li>✓ Valmistettu paikallisesti Tšekin tasavallassa tšekkiläisistä hedelmistä</li>",
        visual_appeal: "Visuaalinen vetovoima",
        quality_perception: "Ainesosien koettu laatu",
        health_perception: "Mielikuva terveellisenä välipalana",
        q2_intent: "Ostaisitko Berrie-brändiä, jos sitä olisi saatavilla kaupassasi?",
        intent_1: "En varmasti",
        intent_2: "Ehkä en",
        intent_3: "En tiedä",
        intent_4: "Ehkä kyllä",
        intent_5: "Varmasti kyllä",
        q3_title: "3. Hintatuntuma (Berrie 150g)",
        q3_intro: "Vakiopakkaus on 150 grammaa. Minkä pakkauksen hinnan perusteella pitäisit tuotetta seuraavana:",
        psm_1: "Liian halpa (laatu epäilyttäisi)",
        psm_2: "Edullinen (loistava ostos tähän hintaan)",
        psm_3: "Kallis (mutta harkitsisin silti ostamista)",
        psm_4: "Liian kallis (en ostaisi sitä enää)",
        q4_title: "4. Asenne paikallista ruokaa kohtaan",
        q4_local: "Kuinka tärkeää sinulle on, että ruoka on tuotettu paikallisesti?",
        scale_low: "Ei lainkaan (1)",
        scale_high: "Erittäin tärkeää (10)",
        q4_premium: "Oletko valmis maksamaan korkeamman hinnan paikallisesta tuotteesta verrattuna tuontituotteeseen?",
        premium_no: "Ei",
        premium_10: "Kyllä, enintään +10 %",
        premium_25: "Kyllä, +10 % - +25 %",
        premium_more: "Kyllä, jopa yli 25 %",
        submit: "Lähetä kysely",
        success_title: "Kiitos vastauksestasi!",
        success_text: "Vastauksesi on lähetetty akateemiseen tietokantaan."
    }
};

document.addEventListener('DOMContentLoaded', () => {
    // --- LANGUAGE SWITCHER ---
    let currentLang = 'cs';
    const langSelect = document.getElementById('lang-select');
    const langInput = document.getElementById('lang-input');

    function updateLanguage(lang) {
        currentLang = lang;
        langInput.value = lang;
        
        if (langSelect) {
            langSelect.value = lang;
        }

        document.querySelectorAll('[data-i18n]').forEach(el => {
            const key = el.dataset.i18n;
            if (translations[lang] && translations[lang][key]) {
                el.innerHTML = translations[lang][key];
            }
        });
    }

    // Auto-detect browser language
    const browserLang = navigator.language || navigator.userLanguage;
    const supportedLangs = Object.keys(translations);
    const detectedLang = browserLang ? browserLang.split('-')[0].toLowerCase() : 'cs';
    
    if (supportedLangs.includes(detectedLang)) {
        updateLanguage(detectedLang);
    } else {
        updateLanguage('cs');
    }

    if (langSelect) {
        langSelect.addEventListener('change', (e) => updateLanguage(e.target.value));
    }

    // --- NAVIGATION LOGIC ---
    const nextBtns = document.querySelectorAll('.next-btn');
    const prevBtns = document.querySelectorAll('.prev-btn');
    const groups = document.querySelectorAll('.question-group');
    const progressBar = document.getElementById('progress');
    const form = document.getElementById('survey-form');
    const totalSteps = groups.length - 1; 

    function validateStep(stepIndex) {
        const currentGroup = document.getElementById(`step-${stepIndex}`);
        if (!currentGroup) return true;

        // Get all required inputs, and ALL radio buttons in this group
        const requiredInputs = currentGroup.querySelectorAll('input[required]');
        const allRadios = currentGroup.querySelectorAll('input[type="radio"]');
        let isValid = true;
        const radioGroups = {};
        
        // Find which radio groups actually have a required attribute
        const requiredRadioNames = new Set();
        requiredInputs.forEach(input => {
            if (input.type === 'radio') {
                requiredRadioNames.add(input.name);
            } else if (!input.value.trim()) {
                isValid = false;
                input.style.borderColor = 'red';
            } else {
                input.style.borderColor = '';
            }
        });

        // Group all radios by name, but only if they are in a required group
        allRadios.forEach(radio => {
            if (requiredRadioNames.has(radio.name)) {
                if (!radioGroups[radio.name]) {
                    radioGroups[radio.name] = [];
                }
                radioGroups[radio.name].push(radio);
            }
        });

        for (const groupName in radioGroups) {
            const isChecked = radioGroups[groupName].some(radio => radio.checked);
            if (!isChecked) {
                isValid = false;
                radioGroups[groupName].forEach(radio => {
                    const card = radio.closest('.radio-card') || radio.parentElement;
                    card.style.outline = '1px solid red';
                    setTimeout(() => card.style.outline = '', 2000);
                });
            }
        }
        return isValid;
    }

    function goToStep(targetIndex) {
        groups.forEach(g => g.classList.remove('active'));
        document.getElementById(`step-${targetIndex}`).classList.add('active');
        
        if (targetIndex === 0) {
            progressBar.style.width = '0%';
        } else if (targetIndex === 'success') {
            progressBar.style.width = '100%';
            progressBar.style.backgroundColor = 'var(--success)';
        } else {
            const progress = (targetIndex / (totalSteps - 1)) * 100;
            progressBar.style.width = `${progress}%`;
        }
    }

    nextBtns.forEach(btn => {
        btn.addEventListener('click', (e) => {
            const currentStep = e.target.closest('.question-group').id.replace('step-', '');
            const targetStep = e.target.dataset.target;
            
            if (currentStep === '0' || validateStep(currentStep)) {
                goToStep(targetStep);
            } else {
                alert(currentLang === 'cs' ? 'Prosím vyplňte všechny povinné otázky.' : 'Please fill all required questions.');
            }
        });
    });

    prevBtns.forEach(btn => {
        btn.addEventListener('click', (e) => {
            const targetStep = e.target.dataset.target;
            goToStep(targetStep);
        });
    });

    // --- SLIDERS UPDATE LOGIC ---
    const sliders = document.querySelectorAll('input[type="range"]');
    sliders.forEach(slider => {
        slider.addEventListener('input', (e) => {
            const display = e.target.parentElement.querySelector('.val-display');
            if(display) display.textContent = `${e.target.value}/10`;
        });
    });

    // --- FORM SUBMISSION (WITH BACKEND) ---
    form.addEventListener('submit', async (e) => {
        e.preventDefault();
        
        // Anti-spam check
        const honeypot = document.querySelector('.honeypot').value;
        if (honeypot !== "") {
            console.log("Spam detected.");
            return;
        }
        
        if (validateStep(4)) { 
            const submitBtn = form.querySelector('button[type="submit"]');
            submitBtn.disabled = true;
            submitBtn.textContent = '...';

            const formData = new FormData(form);
            const data = Object.fromEntries(formData.entries());
            
            try {
                const response = await fetch('/submit', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(data)
                });
                
                if(response.ok) {
                    goToStep('success');
                } else {
                    alert('Error saving data. Please try again.');
                    submitBtn.disabled = false;
                }
            } catch (err) {
                console.error('Submit error:', err);
                alert('Connection error.');
                submitBtn.disabled = false;
            }
        } else {
            alert(currentLang === 'cs' ? 'Prosím vyplňte všechny povinné otázky.' : 'Please fill all required questions.');
        }
    });
});
