# latexmk configuration (LuaLaTeX)
$pdf_mode = 4;             # 4 = lualatex
$interaction = 'nonstopmode';
$silent = 1;

# Bibliography
$bibtex_use = 1;           # let latexmk run biber/bibtex as needed

# Glossaries (makeglossaries)
add_cus_dep('glo', 'gls', 0, 'makeglossaries');
add_cus_dep('acn', 'acr', 0, 'makeglossaries');
sub makeglossaries {
  my ($base_name, $path) = fileparse( $_[0] );
  return system("makeglossaries '$base_name'");
}

$clean_ext .= ' acn acr alg glo glg gls glsdefs ist loa lol lot out run.xml bbl blg bcg';
